# See documentation at https://goreleaser.com
before:
  hooks:
    - go mod download

release:
  github:
  draft: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - arm
    - arm64
    - amd64
    - riscv64
